// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.unlv.cs.socialwebspider.domain;

import edu.unlv.cs.socialwebspider.domain.Profile;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Profile_Roo_Configurable {
    
    declare @type: Profile: @Configurable;
    
}
